### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by jelpsIT** [mardahl/invoke-IntunePolicySync#1]
error-
Importing Powershell modules for Intune
Connecting to Graph
Getting Windows device list
No Windows devices found in Intune (You might want to verify this manually in the Intune Portal)
Done.

Used this for months perfectly, nothing has changed in our Intune tenant.

Any ideas?

**Comment by mardahl** [comment]
Microsoft made som changes around the authentication with the well known app registrations that the microsoft intune graph module uses.

So a completely new script is needed that uses a custom app registration.

As I don't use this script my self any more, I am unable to set aside time to maintain a new version. so this is one for the grave :/
